# Generated by Django 4.0.4 on 2022-06-02 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('status', models.CharField(choices=[('Recently Added', 'Recently Added'), ('Most Watched', 'Most Watched'), ('Top Rated', 'Top Rated')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(choices=[('ALL', 'ALL'), ('KIDS', 'KIDS'), ('ADULTS', 'ADULTS')], default='ALL', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('age_limit', models.CharField(choices=[('ALL', 'ALL'), ('KIDS', 'KIDS'), ('ADULTS', 'ADULTS')], max_length=50)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('movies', models.ManyToManyField(related_name='watched_movies', to='app.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
