# Generated by Django 4.0.4 on 2022-06-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
